apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name | lower | replace(" ", "-") }}
  description: ${{ values.description }}
  tags:
    - azure
    - vm
    - infrastructure
    - terraform
    - ${{ values.location | lower | replace(" ", "-") }}
    - ${{ values.osImage | lower | replace(" ", "-") }}
  links:
    - url: https://dev.azure.com/${{ values.organization }}/${{ values.project }}/_build?definitionId=${{ values.pipelineId }}
      title: Azure DevOps Provisioning Pipeline
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Dynamically map organization and project from Scaffolder parameters
    dev.azure.com/project: "${{ values.organization }}/${{ values.project }}"
    # Optionally map the pipeline ID if your specific plugin version supports it
    dev.azure.com/build-definition: "${{ values.pipelineId }}"
    
spec:
  type: virtual-machine
  owner: ${{ values.owner | lower | replace(" ", "-") }}
  system: azure-infrastructure